name:  Bug Report
description: We can only fix problems we know about...
labels: ["bug"]
assignees:
  - umlaeute
body:
  - type: input
    id: gemversion
    attributes:
      label: Gem Version
      description: What is the exact version of Gem you are using (as printed in the Pd-console)
      placeholder: v0.94-312-g78fe990a0
    validations:
      required: true
  - type: input
    id: pdversion
    attributes:
      label: Pd Version
      description: Which version of Pd are you using?
      placeholder: 0.54-1
  - type: dropdown
    id: OS
    attributes:
      label: Which Operating System are you using?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - other
  - type: input
    id: osversion
    attributes:
      label: OS Version
      description: Which version of the Operating System are you using?
      placeholder: Ubuntu/4.10 "Warty"
  - type: dropdown
    id: arch
    attributes:
      label: Which CPU are you using?
      multiple: true
      options:
        - amd64/x86_64 ("64bit Intel")
        - i386 ("32bit Intel")
        - arm64 ("64bit ARM"; e.g. Apple Silicon,...)
        - arm ("32bit ARM"; e.g. Raspberry Pi,...)
        - other

  - type: textarea
    id: details
    attributes:
      label: Detail
      description: What went wrong?
      placeholder: |
        What did you do, what did you expect, what happened?
    validations:
      required: true
