name: Build and run typesizes
on: push

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake .
      - name: Build
        run: |
          cmake --build .
      - name: Run
        run: |
          ./typesizes

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake .
      - name: Build
        run: |
          cmake --build .
      - name: Run
        run: |
          ./typesizes

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake .
      - name: Build
        run: |
          cmake --build .
      - name: Run
        run: |
          dir
          ./typesizes.exe
